"""Add approval and creator to ClassSchedule

Revision ID: 3858fd8b02e2
Revises: 6b7a956813ba
Create Date: 2026-02-19 17:14:59.221970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3858fd8b02e2'
down_revision = '6b7a956813ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_class_schedules_created_by', 'users', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_schedules', schema=None) as batch_op:
        batch_op.drop_constraint('fk_class_schedules_created_by', type_='foreignkey')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
