"""add_nupay_cpf_recurring_fields

Revision ID: 4afe69b3d779
Revises: e7c2f32393e7
Create Date: 2026-01-23 12:02:43.778057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4afe69b3d779'
down_revision = 'e7c2f32393e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recurring_interval_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('welcome_xp_bonus', sa.Integer(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nupay_reference_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nupay_psp_reference_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nupay_payment_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('nupay_qr_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('nupay_pix_copy_paste', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('nupay_subscription_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('recurring_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('next_billing_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_billing_date', sa.Date(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cpf')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('last_billing_date')
        batch_op.drop_column('next_billing_date')
        batch_op.drop_column('recurring_status')
        batch_op.drop_column('nupay_subscription_id')
        batch_op.drop_column('is_recurring')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('payment_method')
        batch_op.drop_column('nupay_pix_copy_paste')
        batch_op.drop_column('nupay_qr_code')
        batch_op.drop_column('nupay_payment_url')
        batch_op.drop_column('nupay_psp_reference_id')
        batch_op.drop_column('nupay_reference_id')

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('welcome_xp_bonus')
        batch_op.drop_column('recurring_interval_days')
        batch_op.drop_column('is_recurring')

    # ### end Alembic commands ###
