"""add notes and hydration reminder to booking

Revision ID: 5dc799a93b70
Revises: 9433ef7de92f
Create Date: 2026-01-28 17:12:51.329722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc799a93b70'
down_revision = '9433ef7de92f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_hydration_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('reminder_hydration_sent')

    # ### end Alembic commands ###
