"""Add gender segregation fields

Revision ID: 650916102328
Revises: a1b2c3d4e5f6
Create Date: 2026-01-28 16:31:28.108588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650916102328'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_slot_genders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('is_forced', sa.Boolean(), nullable=True),
    sa.Column('forced_by_id', sa.Integer(), nullable=True),
    sa.Column('forced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['forced_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['class_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'date', name='unique_schedule_date_gender')
    )
    with op.batch_alter_table('modalities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_gender_segregation', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=True))

    with op.batch_alter_table('whatsapp_templates', schema=None) as batch_op:
        batch_op.alter_column('trigger',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PAYMENT_CONFIRMED', 'CLASS_REMINDER_24H', 'CLASS_REMINDER_2H', 'CREDITS_EXPIRING', 'CREDITS_EXPIRING_1D', 'CREDITS_EXPIRED', 'CREDITS_DEPLETED', 'ACHIEVEMENT_UNLOCKED', 'XP_CONVERSION_AUTO', 'XP_CONVERSION_MANUAL', 'XP_GOAL_NEAR', 'PAYMENT_OVERDUE', 'SUBSCRIPTION_BLOCKED', 'SUBSCRIPTION_CANCELLED', 'WELCOME', 'CUSTOM', name='templatetrigger'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_templates', schema=None) as batch_op:
        batch_op.alter_column('trigger',
               existing_type=sa.Enum('PAYMENT_CONFIRMED', 'CLASS_REMINDER_24H', 'CLASS_REMINDER_2H', 'CREDITS_EXPIRING', 'CREDITS_EXPIRING_1D', 'CREDITS_EXPIRED', 'CREDITS_DEPLETED', 'ACHIEVEMENT_UNLOCKED', 'XP_CONVERSION_AUTO', 'XP_CONVERSION_MANUAL', 'XP_GOAL_NEAR', 'PAYMENT_OVERDUE', 'SUBSCRIPTION_BLOCKED', 'SUBSCRIPTION_CANCELLED', 'WELCOME', 'CUSTOM', name='templatetrigger'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gender')

    with op.batch_alter_table('modalities', schema=None) as batch_op:
        batch_op.drop_column('requires_gender_segregation')

    op.drop_table('schedule_slot_genders')
    # ### end Alembic commands ###
