"""add referral_code to users

Revision ID: 6b7a956813ba
Revises: 884df585d5d1
Create Date: 2026-02-13 05:59:51.755395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7a956813ba'
down_revision = '884df585d5d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=12), nullable=True))
        batch_op.create_unique_constraint('uq_users_referral_code', ['referral_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_referral_code', type_='unique')
        batch_op.drop_column('referral_code')

    # ### end Alembic commands ###
