"""Add training templates

Revision ID: 884df585d5d1
Revises: b5e8f9a1c2d3
Create Date: 2026-02-12 16:12:42.877970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884df585d5d1'
down_revision = 'b5e8f9a1c2d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal', sa.Enum('HYPERTROPHY', 'FAT_LOSS', 'STRENGTH', 'HEALTH', 'SPORT', name='traininggoal'), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order_in_template', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['training_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps_range', sa.String(length=20), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('weight_suggestion', sa.String(length=50), nullable=True),
    sa.Column('order_in_session', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['template_session_id'], ['template_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commission_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_entries_professional_id'))
        batch_op.drop_index(batch_op.f('ix_commission_entries_status'))

    with op.batch_alter_table('payout_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payout_batches_professional_id'))
        batch_op.drop_index(batch_op.f('ix_payout_batches_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payout_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payout_batches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_batches_professional_id'), ['professional_id'], unique=False)

    with op.batch_alter_table('commission_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_entries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_entries_professional_id'), ['professional_id'], unique=False)

    op.drop_table('template_exercises')
    op.drop_table('template_sessions')
    op.drop_table('training_templates')
    # ### end Alembic commands ###
