"""add reminder_sent to health_screening

Revision ID: 9433ef7de92f
Revises: c2ec56659fcf
Create Date: 2026-01-28 17:03:17.643470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9433ef7de92f'
down_revision = 'c2ec56659fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_screenings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_sent', sa.Boolean(), nullable=True))

    with op.batch_alter_table('whatsapp_templates', schema=None) as batch_op:
        batch_op.alter_column('trigger',
               existing_type=sa.VARCHAR(length=22),
               type_=sa.Enum('PAYMENT_CONFIRMED', 'CLASS_REMINDER_24H', 'CLASS_REMINDER_2H', 'CREDITS_EXPIRING', 'CREDITS_EXPIRING_1D', 'CREDITS_EXPIRED', 'CREDITS_DEPLETED', 'ACHIEVEMENT_UNLOCKED', 'XP_CONVERSION_AUTO', 'XP_CONVERSION_MANUAL', 'XP_GOAL_NEAR', 'PAYMENT_OVERDUE', 'SUBSCRIPTION_BLOCKED', 'SUBSCRIPTION_CANCELLED', 'WELCOME', 'HEALTH_SCREENING_EXPIRING', 'HEALTH_SCREENING_EXPIRING_1D', 'CUSTOM', name='templatetrigger'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_templates', schema=None) as batch_op:
        batch_op.alter_column('trigger',
               existing_type=sa.Enum('PAYMENT_CONFIRMED', 'CLASS_REMINDER_24H', 'CLASS_REMINDER_2H', 'CREDITS_EXPIRING', 'CREDITS_EXPIRING_1D', 'CREDITS_EXPIRED', 'CREDITS_DEPLETED', 'ACHIEVEMENT_UNLOCKED', 'XP_CONVERSION_AUTO', 'XP_CONVERSION_MANUAL', 'XP_GOAL_NEAR', 'PAYMENT_OVERDUE', 'SUBSCRIPTION_BLOCKED', 'SUBSCRIPTION_CANCELLED', 'WELCOME', 'HEALTH_SCREENING_EXPIRING', 'HEALTH_SCREENING_EXPIRING_1D', 'CUSTOM', name='templatetrigger'),
               type_=sa.VARCHAR(length=22),
               existing_nullable=False)

    with op.batch_alter_table('health_screenings', schema=None) as batch_op:
        batch_op.drop_column('reminder_sent')

    # ### end Alembic commands ###
