"""add default_duration to modality

Revision ID: 9c64e6536c84
Revises: 5dc799a93b70
Create Date: 2026-01-28 18:39:36.382277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c64e6536c84'
down_revision = '5dc799a93b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modalities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_duration', sa.Integer(), nullable=False, server_default='60'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modalities', schema=None) as batch_op:
        batch_op.drop_column('default_duration')

    # ### end Alembic commands ###
