"""Add health screening models

Revision ID: c2ec56659fcf
Revises: 650916102328
Create Date: 2026-01-28 16:55:46.380569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ec56659fcf'
down_revision = '650916102328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_screenings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('screening_type', sa.Enum('PARQ', 'EMS', 'ELETROLIPO', name='screeningtype'), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('APTO', 'PENDENTE_MEDICO', 'BLOQUEADO', 'EXPIRADO', name='screeningstatus'), nullable=False),
    sa.Column('acceptance_ip', sa.String(length=45), nullable=False),
    sa.Column('acceptance_timestamp', sa.DateTime(), nullable=True),
    sa.Column('accepted_terms', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('medical_certificate_url', sa.String(length=500), nullable=True),
    sa.Column('medical_certificate_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ems_session_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('procedure_type', sa.Enum('PARQ', 'EMS', 'ELETROLIPO', name='screeningtype'), nullable=False),
    sa.Column('frequency_hz', sa.Integer(), nullable=True),
    sa.Column('intensity_ma', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('treatment_area', sa.String(length=100), nullable=True),
    sa.Column('discomfort_reported', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('session_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ems_session_logs')
    op.drop_table('health_screenings')
    # ### end Alembic commands ###
