"""Add credits cost and booking cost

Revision ID: e3afcdcd0213
Revises: c04d5538ab38
Create Date: 2026-01-21 19:58:10.035098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3afcdcd0213'
down_revision = 'c04d5538ab38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_at_booking', sa.Integer(), nullable=False))

    with op.batch_alter_table('modalities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits_cost', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modalities', schema=None) as batch_op:
        batch_op.drop_column('credits_cost')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('cost_at_booking')

    # ### end Alembic commands ###
