"""Add face recognition, training, and CRM models

Revision ID: fd70350773c5
Revises: 9c64e6536c84
Create Date: 2026-02-03 21:12:20.359814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd70350773c5'
down_revision = '9c64e6536c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('muscle_group', sa.Enum('CHEST', 'BACK', 'LEGS', 'SHOULDERS', 'ARMS', 'CORE', 'FULL_BODY', name='musclegroup'), nullable=False),
    sa.Column('video_url', sa.String(length=300), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('equipment_needed', sa.String(length=200), nullable=True),
    sa.Column('difficulty_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('face_recognition_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('face_recognition_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_face_recognition_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('source', sa.Enum('WEBSITE', 'INSTAGRAM', 'REFERRAL', 'WALK_IN', 'GOOGLE_ADS', name='leadsource'), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'VISITED', 'TRIAL', 'PROPOSAL', 'WON', 'LOST', name='leadstatus'), nullable=True),
    sa.Column('interest_goal', sa.String(length=100), nullable=True),
    sa.Column('preferred_schedule', sa.String(length=100), nullable=True),
    sa.Column('budget_range', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(), nullable=True),
    sa.Column('trial_class_date', sa.DateTime(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('lost_reason', sa.String(length=200), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('converted_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['converted_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('converted_user_id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_status'), ['status'], unique=False)

    op.create_table('student_health_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('frequency_score', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('financial_score', sa.Float(), nullable=True),
    sa.Column('tenure_score', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=True),
    sa.Column('requires_attention', sa.Boolean(), nullable=True),
    sa.Column('last_action_taken', sa.String(length=200), nullable=True),
    sa.Column('last_action_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_health_scores', schema=None) as batch_op:
        batch_op.create_index('ix_health_scores_user_date', ['user_id', 'calculated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_health_scores_calculated_at'), ['calculated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_health_scores_requires_attention'), ['requires_attention'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_health_scores_total_score'), ['total_score'], unique=False)

    op.create_table('training_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Enum('HYPERTROPHY', 'FAT_LOSS', 'STRENGTH', 'HEALTH', 'SPORT', name='traininggoal'), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_plans', schema=None) as batch_op:
        batch_op.create_index('ix_training_plans_user_active', ['user_id', 'is_active'], unique=False)

    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('order_in_plan', sa.Integer(), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps_range', sa.String(length=20), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('weight_suggestion', sa.String(length=50), nullable=True),
    sa.Column('order_in_session', sa.Integer(), nullable=False),
    sa.Column('instructor_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.create_index('ix_workout_exercises_session', ['workout_session_id', 'order_in_session'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_encoding', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('face_encoding_version', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('face_registered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('face_last_recognized', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('face_confidence_threshold', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('face_confidence_threshold')
        batch_op.drop_column('face_last_recognized')
        batch_op.drop_column('face_registered_at')
        batch_op.drop_column('face_encoding_version')
        batch_op.drop_column('face_encoding')

    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_index('ix_workout_exercises_session')

    op.drop_table('workout_exercises')
    op.drop_table('workout_sessions')
    with op.batch_alter_table('training_plans', schema=None) as batch_op:
        batch_op.drop_index('ix_training_plans_user_active')

    op.drop_table('training_plans')
    with op.batch_alter_table('student_health_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_health_scores_total_score'))
        batch_op.drop_index(batch_op.f('ix_student_health_scores_requires_attention'))
        batch_op.drop_index(batch_op.f('ix_student_health_scores_calculated_at'))
        batch_op.drop_index('ix_health_scores_user_date')

    op.drop_table('student_health_scores')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_status'))
        batch_op.drop_index(batch_op.f('ix_leads_phone'))
        batch_op.drop_index(batch_op.f('ix_leads_created_at'))

    op.drop_table('leads')
    with op.batch_alter_table('face_recognition_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_recognition_logs_timestamp'))

    op.drop_table('face_recognition_logs')
    op.drop_table('exercises')
    # ### end Alembic commands ###
